service: validateCPF

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: src/handler.validateCPF
    timeout: 60 # seconds
    memorySize: 128 # mb