on:
  push:
    branches:
      - main 

name: Deploy

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        env:
          CI: true
        run: |
          npm ci