name: Deploy Lambda

on:
  push:
    branches: ["dev", "uat", "prd", "main"]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Serverless Framework Configuration
        run: |
          ls -l   # List contents to verify the presence of 'serverless.yml' in the current directory
          cat serverless.yml   

      - name: Deploy using Serverless Framework
        run: |
          npm install -g serverless  
          serverless deploy  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1